version: '2'
services:
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci #设置utf8字符集
    restart: always
    volumes:
      - "/data/mysql:/var/lib/mysql"
    environment:
      TZ: 'Asia/Shanghai'
      PORT:  3306
      MYSQL_ROOT_PASSWORD: 'cloud-app123,.'
    ports:
      - 3306:3306
